/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavbars: typeof import('./src/components/AppNavbars.vue')['default']
    copy: typeof import('./src/components/SupplierContent copy.vue')['default']
    CustomerCart: typeof import('./src/components/CustomerCart.vue')['default']
    CustomerContent: typeof import('./src/components/CustomerContent.vue')['default']
    ErrorContent: typeof import('./src/components/ErrorContent.vue')['default']
    IndexContent: typeof import('./src/components/IndexContent.vue')['default']
    LoadingContent: typeof import('./src/components/LoadingContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupplierContent: typeof import('./src/components/SupplierContent.vue')['default']
  }
}
